title: Archive
author: 최유빈
email: sean9892@gmail.com
url: https://sean9892.github.io
baseurl: ""
description: >
  Something archived.

permalink: /:slug/

favicon: "logo.png"
# goat_counter: "yoursitename"

remote_theme: riggraz/no-style-please

theme_config:
  appearance: "dark" # can be "light", "dark" or "auto"
  back_home_text: "<<<" # customize text for homepage link in post layout
  date_format: "%Y-%m-%d" # customize how date is formatted
  show_description: false # show blog description in home page
  lowercase_titles: false # show titles in lowercase in lists

sass:
  style: compressed

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jektex

jektex:
  cache_dir: ".jektex-cache"
  ignore: ["*.xml"]
  silent: false
  macros:
    - ["\\Q", "\\mathbb{Q}"]
    - ["\\C", "\\mathbb{C}"]
    - ["\\F", "\\mathbb{F}"]

markdown: kramdown
kramdown:
  input: GFM
  highlighter: rouge